version: "3.8"

networks:
  network:

volumes:
  oracledb_vol:

services:

  oracledb:
    image: cocomdidin/oracle-xe-10g:latest
    container_name: oracle-xe-10g
    build:
      context: ./
      dockerfile: ./Dockerfile
    # restart: "always"
    volumes:
      - ./database:/home/database
      - oracledb_vol:/usr/lib/oracle
      # - ./build/env/oracledata/oradata:/opt/oracle/oradata # persistent oracle database data.
      # - ./build/env/oracledata/data-bridge:/data-bridge # just to have someplace to put data into the running container if needed
    ports:
      - "1001:22"
      - "1002:1521"
      - "1003:8080"
    networks:
      - network
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.00"
    #       memory: "100M"
          